version: "3.7"
services:
  dev-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 8080:8080
    entrypoint: /app/docker-dev-server.sh
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    entrypoint: /app/docker-build.sh
  cleaner:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    entrypoint: /app/docker-clean.sh
  deployer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DKR_GIT_NAME
      - DKR_GIT_EMAIL
    volumes:
      - .:/app
    entrypoint: /app/docker-deploy.sh


